// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
// import { env } from './.env';

export const environment = {
	production: true,
	hmr: false,
	version: '1.0',
	//serverUrl: 'https://127.0.0.1:5001',
	baseURL: 'https://api.meinumzug24.eu/api/',
	defaultLanguage: 'de-DE',
	//supportedLanguages: ['en-US', 'de-DE', 'fr-FR', 'tr-TR', 'es-ES', 'ru-RU']
	supportedLanguages: ['en-US', 'de-DE', 'tr-TR'],
};
